"""add RoleTemplate.default_slots

Revision ID: 1822880cddbb
Revises: 3537651273c7
Create Date: 2026-08-12 23:22:34.723504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1822880cddbb'
down_revision = '3537651273c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # RĘCZNA POPRAWKA: autogenerate zostawił NOT NULL bez server_default, co psuje
    # się na istniejących wierszach (SQLite nie wie, czym je wypełnić). Dodajemy
    # server_default='1', zgodnie z Python-owym default=1 w modelu.
    with op.batch_alter_table('role_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_slots', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_templates', schema=None) as batch_op:
        batch_op.drop_column('default_slots')

    # ### end Alembic commands ###
