"""add EventRole.sort_order

Revision ID: 9d405937f225
Revises: b021edc3475d
Create Date: 2026-08-14 00:38:47.042267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d405937f225'
down_revision = 'b021edc3475d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # RĘCZNA POPRAWKA: NOT NULL bez server_default psuje się na istniejących
    # wierszach. Zgodnie z Python-owym default=0 w modelu; istniejące wiersze
    # więc na starcie sortują się alfabetycznie po nazwie (nadal grupuje takie
    # same role obok siebie) - dopiero nowo tworzone dostają realny sort_order
    # z RoleTemplate.
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_roles', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
