"""add SaturdayEvent.is_cancelled and cancel_reason

Revision ID: b021edc3475d
Revises: 1822880cddbb
Create Date: 2026-08-12 23:58:23.718241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b021edc3475d'
down_revision = '1822880cddbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # RĘCZNA POPRAWKA: is_cancelled jest NOT NULL - bez server_default upgrade
    # wywaliłby się na już istniejących wierszach (SQLite nie wie, czym je
    # wypełnić). Zgodnie z Python-owym default=False w modelu.
    with op.batch_alter_table('saturday_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saturday_events', schema=None) as batch_op:
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###
